server:
  port: 8080

spring:
  application:
    name: movie-ticket-reservation

  datasource:
    url: jdbc:mysql://localhost:3306/movie_ticket_reservation
      ?useSSL=false
      &serverTimezone=Asia/Shanghai
      &characterEncoding=utf8
      &allowPublicKeyRetrieval=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false   # 前端调试必开
    prefix: classpath:/templates/
    suffix: .html

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.movie_ticket_reservation.entity
  configuration:
    map-underscore-to-camel-case: true   # movie_id -> movieId
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ⭐ 打印 SQL

logging:
  level:
    root: info
    com.example.movie_ticket_reservation: debug
    org.mybatis: debug
    org.springframework.jdbc: debug
